### ISSUE TITLE
Listening from desktop makes my phone play "anti-ad"

### ISSUE THREAD

**Issue by hovancik** [abertschi/ad-free#16]
Hey, 

when I am listening on desktop, and there is an ad, ad-free starts playing 'anti-ad'

**Comment by abertschi** [comment]
Hi back!

Spotify broadcasts ads to all active clients. So when an ad occurs on your computer and your phone runs the Spotify app, the ad will also occur on your phone. 

There is currently no way I can detect this behaviour with ad-free, but when you quit the Spotify app on mobile, this should not happen afaik.

**Comment by hovancik** [comment]
I'll try to force-quit or something. So far spotify on Android always turns itself on.
