### ISSUE TITLE
Completely non-working on Fire OS (5.6.0.1)

### ISSUE THREAD

**Issue by vaguerant** [abertschi/ad-free#19]
Possibly out of scope, obviously.

Fire OS is the customized version of Android used on Amazon "Fire" devices (most notably tablets). The current version is based on Android 5.1.1 Lollipop. Broadly, standard Android app compatibility is good on Fire OS. It's possible to sideload F-Droid and install other apps than those explicitly intended for Fire OS.

However, Ad-Free doesn't seem to work at all on this setup. There's no notification to ensure activity is maintained and Spotify ads are not in any way affected by the app running. The mechanism by which similar apps function seems to do the job on Fire OS: the app "Spotify Admodify" similarly triggers its own notification then monitors Spotify notifications and is able to mute its ads without issue.

**Comment by abertschi** [comment]
Hi there, thanks for shouting out to me.
There is no support for Lollipop. I will flag this issue as an enhancement and perhaps debug it on Lollipop the next time I do maintenance work for this project.

keep it up

**Comment by vaguerant** [comment]
Thanks, fingers crossed over here.

Minor note: the following message appears on the F-Droid app page when installing Ad-Free: "This version requires Android 5.0 or newer." Maybe the minimum version should be upped until support on lower versions is implemented.

**Comment by abertschi** [comment]
fixed in version #52
