### ISSUE TITLE
Non-working android 7.1.2 MIUI 9.5

### ISSUE THREAD

**Issue by pinkymistico** [abertschi/ad-free#24]
Thank you excellent app, but didn't work in my new cell phone from xiaomi.

Good work.

**Comment by abertschi** [comment]
Have you had a phone with MIUI before that worked with Ad-Free? I don't know how much of MIUI is custom but the currently implemented ad-detector relies on specific notification attributes set by the Android runtime.

some trouble shooting hints:
- try to reinstall Ad-Free
- try to run it with a Spotify version which is listen in the README file.
- does the Ad-Free notification appear when ads are active? 
- does the Ad-Free notification appear if you press the ♫ - icon on the second screen in Ad-Free to test a selected plugin?

**Comment by Nanco300** [comment]
Here on Redmi 2 with Android 8.1 the songs are halting 'randomly'

**Comment by abertschi** [comment]
The upcoming release version 1.1 will fix compatibility issues with miui10

**Comment by abertschi** [comment]
please file a new issue if problems persist.
