### ISSUE TITLE
does it should work with android auto?

### ISSUE THREAD

**Issue by 2803media** [abertschi/ad-free#31]
Thanks for your answer

**Comment by abertschi** [comment]
Hi there, I never tested it on Android auto. ad-free relies on Android notifications as they are available on phones. Did you run it on Android auto?

**Comment by 2803media** [comment]
When you use android auto I guess it use the app on the phone (just an hypothesis). To answer your question I use the phone where your app is installed and the ads aren't mute. I try to find a way to make it works for Android auto (as Android TV too ;) )

**Comment by abertschi** [comment]
![image](https://user-images.githubusercontent.com/2311941/55674088-21703180-58b0-11e9-9166-6b90630e8279.png)
