### ISSUE TITLE
Sound is played from phone speaker when headphones are plugged in

### ISSUE THREAD

**Issue by hydrandt** [abertschi/ad-free#32]
Phone: Samsung S8, latest vendor firmware (Android 9).

When listening to Spotify with headphones (wired, jack), the interdimensional cable is played on the phone's loudspeaker.

Thanks for the awesome software! ;-)

**Comment by abertschi** [comment]
I haven't tested the app with Android 9, can other users verify this behaviour? Samsung uses a modified version of Android compared to google's stock version. In the meantime you can switch to the mute-plugin. Does mute still work?

**Comment by hydrandt** [comment]
Yep, mute works fine. Happy to help to troubleshoot - but I know very little about Android.

**Comment by abertschi** [comment]
so i tested the app on android 9, on a stock rom xiaomi Mi A1 and I did not notice your findings. Seems like the issue is Samsung rom specific. Without such a phone
there is not much I can do as tackling down the issue requires try and error and debugging.

**Comment by hydrandt** [comment]
Thanks for checking! My life will have to go on without random intakes of interdimensional cable commercials.

**Comment by losparviero** [comment]
On stock Pie (Nokia 6.1 Plus), & can say that I don't have this problem. I did notice, pretty abruptly, that the app doesn't adhere to media volume settings & instead plays at call volume. One of my ears can attest to that.

Having experienced issues between switching jack & speaker output with HTC's Boomsound, try turning off the Dolby enhancement which Samsung includes.

If that doesn't do it then the issue can be boiled down to Samsung's modifications to volume channnels, in which case, I doubt much can be done without root?

As a last ditch effort, try & see if Samsung provides an option to ring via the loudspeaker for calls even when headphones are plugged in, & turn it off.
