### ISSUE TITLE
Ads back on on Volume up during interdimensional cable

### ISSUE THREAD

**Issue by mordeng** [abertschi/ad-free#36]
-One Plus 7 Pro
-Oxygen OS 9.5.11 (Android 9.x port)
-Phone is connected to bluetooth speaker/headset.
-Interdimensinal cabel setting

On changing volume it also changes the mute setting for ads:

--->I can hear spotify ads as well as interdimensional cable

to reproduce:

turn on interdimensional cable
listen to spotify and wait for ads
turn volume louder -->ads  and interdimensional cable plays simultaneously

Note; This setting is also saved, so next time ads show up it still plays simultaneously

Temporary fix:
- turn off spotify, 
- open ad-free
- re-apply the setting

**Comment by abertschi** [comment]
Hi mordeng,

This is a side effect of how playback of music in Ad-Free is currently implemented. If you adjust volume during ad blocking, your phone will change the volume of STREAM_MUSIC, ie the channel through which Spotify plays ads. As a result STREAM_MUSIC is unmuted and you get your described behavior.

**Comment by abertschi** [comment]
You can adjust playback volume of Ad-Free in the settings of the interdimensional cable or the music plugin.
