### ISSUE TITLE
Interdimentional cable only plays during the 1st ad.

### ISSUE THREAD

**Issue by Bebop182** [abertschi/ad-free#37]
OnePlus One
Lineage 15

Spotify started recently to push multiple ads back to back, Most often than not the exact same ad is played twice, that's what motivated me to look for a fix.
While ad-free does a great job, only one clip of Interdimentional Cable (IC) is played and then mute. Is there a way you could loop the IC while the ads finish playing?

Regardless thanks a lot for your work

**Comment by abertschi** [comment]
this is certainly doable. I will flag it as a feature request.
