### ISSUE TITLE
Unmutes a few seconds too early, playing endings of ads.

### ISSUE THREAD

**Issue by roadie** [abertschi/ad-free#39]
Using Essential phone PH-1, using latest version of Spotify and Ad-Free. Most of the time, the phone would unmute before the ad finishes so a few seconds of ads would be played. Is there any way to unmute at the right time? Even just extend a few more seconds to mute the music would be less distracting.

**Comment by abertschi** [comment]
I don't observe your described behavior on my devices. Does it happen with all ads? What ad-blocking plugin did you select in ad-free settings? Can you create a video of your phone showing the notification drawer and the spotify and ad-free notifications when ads play? If you do so I will consider implementing such adjustment parameters but I first want to see the issue myself.

**Comment by roadie** [comment]
It doesn't happen to all the ads. And the behaviour is not the same all the time either. Sometimes it blocks the ads perfectly, sometimes it ends one second before the ad finishes, sometimes a free seconds, and occasionally half the ad is played. 

I chose mute audio.

I don't have time to create a video to show this yet. I have to find another phone to record it so it'll take some effort. But basically the behaviour of the Ad-Free notification appears normal; it's shows the blocking and mute sign when it mute, and neck to normal when the blocking stops; but it just stops a bit early sometimes.

**Comment by abertschi** [comment]
If the behavior is irregular, there is not much I can do. I was thinking of adding an option to delay the action of unmuting. But this option will be applied for all unmutes, as there is no obvious way to recognize when to unmute and when to delay before unmute.

Currently, once one of the ad-detectors recognizes that there is no more ad playing, ad-free will unmute the stream audio channel and hide its notification.

https://github.com/abertschi/ad-free/blob/92329012918c492c5349efc2e2000c0da773bc0b/app/src/main/java/ch/abertschi/adfree/AdStateController.kt#L75-L83

**Comment by roadie** [comment]
Thanks for your attention. To be honest, I think the delay unmute option
would still be quite helpful because although it's irregular, most of the
ads are played for a second at the end. If the option is there, then those
who has similar problem can use it. I would set it to one or two seconds
still and cut out the ads, if it sacrifices the first second or two of the
next song, I think it's still a good trade-off.

At the same time, is there anything else you could suggest to
troubleshoot so I can find the root cause of this problem?

**Comment by abertschi** [comment]
> At the same time, is there anything else you could suggest to
> troubleshoot so I can find the root cause of this problem?

The only thing on top of my head is Settings/Playback/Crossfade option in the Spotify app, did you enable it? It may cause some interference with the notifications. If so, disable it.

**Comment by roadie** [comment]
Thanks for the suggestion. The settings in Spotify should be all in default
mode, but I checked; the crossfade is off, Gapless is off. There's an
option called Automix and it's on. Don't know what it is, but what I'll do
is to turn it off and see if it makes any difference. Will report back.

Thanks.

**Comment by abertschi** [comment]
fixed in version #52
