### ISSUE TITLE
Doesn't always unmute after an ad.

### ISSUE THREAD

**Issue by weirdal3333** [abertschi/ad-free#47]
I use this app with both Spotify and Spotify Stations. It works on both. 

HOWEVER, sometimes, on Bluetooth, it doesn't unmute. I think that the Bluetooth device is lagging the volume up rocker. 

A potential fix is to make an option for slowly fading the music track in. Maybe a 'FX' option list would work, where I could set how fast the fade happened. Right now, I have my phone set to maximum volume, and my speaker is adjusted accordingly. I'm going to mess with the developer options and see if changing the absolute volume function fixes it.

**Comment by weirdal3333** [comment]
![Screenshot_20191223-112721](https://user-images.githubusercontent.com/3537180/71368906-3cd2b800-2577-11ea-97dd-6a48f2ff8382.png)

Disabling absolute volume fixed it. I have an umidigi A3 pro, unmodified stock.

**Comment by abertschi** [comment]
fixed in version #52
