### ISSUE TITLE
"Play until end" - funny but confusing

### ISSUE THREAD

**Issue by kojid0** [abertschi/ad-free#48]
I really like that some developers try to put some funny features into their apps. Really appreciate them making me smiling. But I don't understand "Play until end" option...

There should be two options only: "play local music file until spotify ad ends" or "play until end of music file, regardless if spotify ad already ended before".

**Comment by abertschi** [comment]
"play until end" plays the local audio track until its end. If it is set to yes (or any equivalent word), it plays local music until the end of the local audio track, regardless if ads have already ended. Spotify is only unmuted once local audio finishes. if it is set to no, Spotify is unmuted as soon as a detector detects no more ads. yes and no options alternate after each click.

**Comment by abertschi** [comment]
While I appreciate your feedback I am currently not planning to change this behavior.

**Comment by abertschi** [comment]
fixed in version #52

**Comment by kojid0** [comment]
> fixed in version #52

Thank you so much! I very appreciate your work 🙏
