### ISSUE TITLE
Remove "full network access"-permission

### ISSUE THREAD

**Issue by kojid0** [abertschi/ad-free#49]
What does Ad-Free need full network access for? I guess it has been added in order to download the music file of Interdimensional Cable but this feature has been discontinued.

Since As-Free has full access to notifications, it could technically (!) upload user notifications somewhere (yes, it's open source and in F-Droid). I truly believe that it doesn't, but if this permission is not necessarily needed, it should be removed.

Also, for what does the app need "view network connections" and "read the contents of your shared storage" permissions?

**Comment by abertschi** [comment]
The interdimensional cable plugin uses network access. Also there is a legacy feature that checks for a new release on github and shows a notification within the app. But this is currently disabled. Ad-free does not upload personal information. I do not even track install stats. The only distribution source for binaries is fdroid which guarantees that fdroid signed binaries match a given and available version of source code.

The manifest contains these permissions:
```
   <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```
Internet is needed for network sockets while access_network_state to check if there is an internet connection available at all.

There is a runtime permission to access local storage for the local music plugin. It needs access to storage to read audio files. 

I am not planning to remove internet access in near future, as it does not add functional benefit and requires time. I am planning to rewrite the update reminder such that it is compatible with fdroid to encourage users to upgrade to improved versions of the app. But this has low priority.

**Comment by abertschi** [comment]
Some custom roms provide app level internet access limitation. Lineage OS, or MIUI provide this, as far as I know. You may want to look into these if internet access in general is one of your concerns.

**Comment by kojid0** [comment]
Thank you for clarifying this issue. I was just wondering if this would be an enhancement for more skeptical users (not including me). I'm fully trusting this app since it's open source and on F-Droid. Really enjoying it!
