### ISSUE TITLE
After 1.0, activates on all songs

### ISSUE THREAD

**Issue by ogrefriend** [abertschi/ad-free#50]
I'm running Android 6.0.1. I have tried it with Spotify 8.5.36.747 and the beta 8.5.39.234. It activates as soon as I start playing music on Spotify and will not stop. I tried upgrading to 1.2.1 to see if it worked, as I have been downgrading back to 1.0 each time. I did not keep a copy of the apk, and now it is removed from F-Droid. Is there a way to remedy this or downgrade back to 1.0, so I can use the app? Edit: I have found a copy of the apk from F-Droid's website on the Wayback Machine, which again, does function as expected. Is there any reason why 1.0 works but newer versions do not?

**Comment by abertschi** [comment]
Hi there, What phone do you use?

**Comment by abertschi** [comment]
1.1+ introduces more support for devices. It's possible that these changes trigger false positives on your device. An upcoming version will introduce toggles to disable individual detectors. This may solve your issue. Apart from that the only option to figure out what's wrong is debugging on your particular device.

**Comment by ogrefriend** [comment]
It is a ZTE Z957. Thanks for the insight. Perhaps the upcoming version will be helpful in that regard. For now the older version works a charm. I will make sure to retain the older version as long as I have this phone.

**Comment by abertschi** [comment]
fixed in version #52
