### ISSUE TITLE
30 second sponsored music previews are not muted

### ISSUE THREAD

**Issue by forever-and-a-day** [abertschi/ad-free#60]
Spotify disguises these ads as songs, but they are only 30 seconds and begin with the artist telling listeners to check out their music/album on Spotify.

**Comment by abertschi** [comment]
With so little information there is nothing that can be done. Record all notifications including the ad with the recording feature described here:https://abertschi.github.io/ad-free/troubleshooting/troubleshooting.html#org1b88f13 and post the recording file in a new issue on github.
