### ISSUE TITLE
Download songs to play later

### ISSUE THREAD

**Issue by PCChazter** [abertschi/ad-free#61]
A cool option would be to have the app download up to a certain amount of songs from Spotify to play later instead of the ads. You could have it replace already used songs with another song from Spotify.

**Comment by abertschi** [comment]
I agree, this would be cool. However, Spotify does not support such service to download tracks off their platform. Their offline cache is not accessible by other players and resides encrypted. A much more straightforward approach is the existing music player plugin of ad-free. Or to build a plugin which uses an alternative service such as soundcloud during ads. Though, they may show ads themselves.
