### ISSUE TITLE
SoundCloud not working 

### ISSUE THREAD

**Issue by dundunn** [abertschi/ad-free#62]
It's not been working for quite a while now and I'm not sure if it's only me.

**Comment by abertschi** [comment]
As a starter you can try the troubleshooting steps here: 
https://abertschi.github.io/ad-free/troubleshooting/troubleshooting.html

If the issue persists post the following pieces of information:
- your phone model
- version of android
- version of soundcloud
- version of ad-free

As stated in the troubleshooting steps under _6.2 Record notifications for a new detector_, enable the recorder for soundcloud and make sure you capture the ad. Send me the capture file. The storage location is displayed when you enable the soundcloud recorder. It is in `./Android/data/ch.abertschi.adfree/files/adfree-soundcloud.txt` on your internal phone storage. With the capture file we can further investigate your issue.

**Comment by dundunn** [comment]
Sorry for the late response. Always when I tried to test it I didn't get any ads.
I've activated the experimental detector for SoundCloud and it's working again. I'm not quite sure but I think it's like that since I've updated my OnePlus 3T to Android 10. Before that I didn't have to activate that feature.

**Comment by abertschi** [comment]
Oh I see. You updated ad-free as well. Before version 2.0 the experimental soundcloud detector was not opt-in; there was no feature implemented to toggle active detectors in the app.
