### ISSUE TITLE
create better logo

### ISSUE THREAD

**Issue by abertschi** [abertschi/ad-free#63]
If you are good at design and want to contribute to ad-free, shout out here and create a new logo

**Comment by jotbeh** [comment]
Hey abertschi, 

I'm not a professional designer, but I played around with some options and came up with the following idea:

![logo ideas](https://i.imgur.com/Ukt895Q.png)

![in F-Droid](https://i.imgur.com/IzWeUNg.png)

Let me know if you like it, and I will provide you the svg or any other format you need.
Thank you for your work!

**Comment by abertschi** [comment]
Thanks for shouting out and your self initiative! :) :+1:  I think we get somewhere with this but I dont like the reference to Spotify. Maybe we can replace it with some generic sound or speaker symbol. Maybe you have some more ideas ... :) 

Ad-free is not Spotify specific. I don't know how to update the fdroid subtitle, but ad-free is meant to be a opensource and generic audio blocker on Android.

**Comment by jotbeh** [comment]
Ah, I see. Generally, do you have a color scheme in mind? Monochrome? Flat Style or basic clipart?
How do you feel about a Megaphone as the basis?

**Comment by abertschi** [comment]
The colors used throughout the app are simplistic in a grey theme and are as follow:
- color used for non highlighted text is `#C4BCAF`
- highlighted text: `#FFFFFF`
- background and primary color: `#252A2E`

Megaphone sounds good. I would probably go with something simplistic but I do not have more defined ideas in mind. Just be sure that you created the content or otherwise have the right to pass it on to this project.

**Comment by jotbeh** [comment]
so, I tried to keep it simple and came up with this one:

![megaphone logo](https://i.imgur.com/bVlROm9.png)

Is that the right direction?

**Comment by abertschi** [comment]
looking good :+1:

**Comment by jotbeh** [comment]
![megaphone logo variation](https://i.imgur.com/qkvJJEf.png)
trying to make it not as heavy-looking. If you like/want any of these or have some pointers, let me know 👍🏻

**Comment by abertschi** [comment]
cool! I like the 2nd one most. Can you put it into a circle background? To see whether we should use a transparent icon or one with background.

**Comment by jotbeh** [comment]
![megaphone logo circles](https://i.imgur.com/y8X4RXI.png)
I wasn't sure which logo you were referring to, so I included both options.
The colors are the scheme you provided above.

**Comment by abertschi** [comment]
> I wasn't sure which logo you were referring to, so I included both options.

 I was referring to the bottom picture among the two posted sample designs https://github.com/abertschi/ad-free/issues/63#issuecomment-623694082.

This is already looking promising 👍

Can you perhaps experiment with a border around the icon in a similar fashion to this calendar icon:
![image](https://user-images.githubusercontent.com/2311941/81015526-24e13e00-8e5f-11ea-90ee-cd5f6a863728.png)

Or experiment with a shadow such that the megaphone does not look so flat. You do not necessarily have to stick to the color theme of the app.

**Comment by jotbeh** [comment]
![megaphone logo circles](https://i.imgur.com/1fxSNQR.png)
Right direction?

Edit: Added following variations

![megaphone logo circles](https://i.imgur.com/zgvOsOt.png)

Edit 2: Just realized the shadow makes more sense this way

![megaphone logo circles](https://i.imgur.com/ysRsNGr.png)

Edit 3: I don't know how lights/shadows work 😅

![megaphone logo circles](https://i.imgur.com/G9SYAMj.png)

I think I like the very last one best so far.

**Comment by abertschi** [comment]
Cool, very last one is good :+1:  I also like this one:
![image](https://user-images.githubusercontent.com/2311941/81100660-2cf7b700-8f0d-11ea-8743-4cd8a3810cb4.png)


Can you replace the greenish color with white? To see how that would look like. Good job so far ! 🚀

**Comment by jotbeh** [comment]
![megaphone white](https://i.imgur.com/whSxkBS.png)
The color palette is up for debate of course, just started with some that went relatively well with each other. I think the red should probably stay to emphasize the "stop signness", but could play around with hue in accordance with other colors.

**Comment by abertschi** [comment]
I agree, the red should stay 👍. Maybe we can make the red more eye-catchy, brighter, ie. closer to 0xFF. The megaphone may be better visible if it fills out more of the circle 🤔.

**Comment by abertschi** [comment]
![image](https://user-images.githubusercontent.com/2311941/81122009-4d853880-8f30-11ea-9f0b-856dff1186d7.png)

**Comment by jotbeh** [comment]
![megaphone white red](https://i.imgur.com/ukj0B9k.png)
![megaphone white red](https://i.imgur.com/h6jTcGU.png)
![megaphone white red](https://i.imgur.com/Ui69dCy.png)
![megaphone white red](https://i.imgur.com/u7A0nih.png)

**Comment by abertschi** [comment]
Can you upload these four versions as SVG? I will deal with the rest. The logo will make it in the next release. Also, let me know how you want to be credited :+1:

**Comment by jotbeh** [comment]
Glad you like the results. Alright, I'll send an email to the adress on your website.
