### ISSUE TITLE
Bluetooth Headset Error

### ISSUE THREAD

**Issue by Frischid** [abertschi/ad-free#64]
I tried to use the app (F-Droid Version 2.2/36 )on my OnePlus5 (Android 9) with JBL Bluetooth headphones but when the app detected advertise it muted everything instead of playing local music. But with wired headphones all worked well.

I was able to get things work when disabling the last option in following screenshot (sorry only in German)
<img src="https://user-images.githubusercontent.com/25387862/79776559-37735780-8336-11ea-934e-5845fa963c7d.jpg" height="400px"></img>

Perhaps it would be great for other users to add this into the troubleshooting site.

The app is very great, I enjoy listening music, thank you very much!

**Comment by abertschi** [comment]
Thanks for shouting out, I added a note to this issue in the troubleshooting steps.
