### ISSUE TITLE
Cant select music directory

### ISSUE THREAD

**Issue by kaustubhowmick** [abertschi/ad-free#66]
Whenever I click to choose a music directory.

It always say "Whoops, error with chosen directory. Choose a different one"

**Comment by abertschi** [comment]
What directory do you choose? Things like google drive and recent do not work. It has to be a location like /sdcard/Music or the like. A folder on storage.

**Comment by kaustubhowmick** [comment]
I did choose my SD Card, but it still shows the error message, and I choose
the music directory next, again it it showing the error message. I have
attached a screen recording of the same.
I have shared a link to my google drive . Check them out.
https://drive.google.com/open?id=118IThVFPi5q9DSatQ3QhmeT3jm1eGrCh

**Comment by abertschi** [comment]
#84
