### ISSUE TITLE
Deezer support

### ISSUE THREAD

**Issue by cbuctok** [abertschi/ad-free#69]
Hello!
Thank you very much for this app, it saves lives by not stressing drivers and makes travels more fun!

I really love the Spotify support but recently I started to use Deezer and I really really miss ad-free.

#feature-request

**Comment by abertschi** [comment]
Hi there, Thanks for reaching out.
I currently do not have an incentive to implement support for Deezer, as I do not use the service myself. There is also another request for youtube music in my queue.
