### ISSUE TITLE
Mutes when playing a podcast on Spotify

### ISSUE THREAD

**Issue by githubashutoshsoni** [abertschi/ad-free#74]
When ever I play any podcast it automatically mutes. It works fine for ads but it shouldn't happen for my currently playing podcast. I'm using OnePlus 6, android os 10. Oxygen OS 10.3.6

**Comment by abertschi** [comment]
thanks for reaching out. this issue is already reported here: #73

**Comment by abertschi** [comment]
I am currently occupied with other things, but what you can do is to record notifications as described here:
https://abertschi.github.io/ad-free/troubleshooting/troubleshooting.html

and send me the recording.

**Comment by githubashutoshsoni** [comment]
Sure, I will add the recording.

**Comment by abertschi** [comment]
Does the issue still exist?
