### ISSUE TITLE
Feature request: Capture crash report from the app itself

### ISSUE THREAD

**Issue by shuvashish76** [abertschi/ad-free#76]
[Newpipe](https://github.com/TeamNewPipe/NewPipe) capture bug/crash reports directly from the app & there is option to send crash report by mail or just posting it on github.

It would be nice if ad-free follow the same method to send crash reports.

I think newpipe uses https://github.com/ACRA/acra for this.

I know nothing about coding, please do check if it is possible or not..

**Comment by abertschi** [comment]
A privacy friendly crash reporting feature is already implemented:
https://github.com/abertschi/ad-free/tree/master/app/src/main/java/ch/abertschi/adfree/crashhandler

And I am receiving email based reports. Why it did not lead to report request in your issue #75 is yet to be figured out.
