### ISSUE TITLE
request: Accuradio support

### ISSUE THREAD

**Issue by unseenlarks** [abertschi/ad-free#80]
thank you very much for this app, still works like a charm. in addition to adding a +1 to previously posted requests for other apps (notably Deezer and Spotify Lite) i was wondering if it could be extended to Accuradio. thank you for your time.

**Comment by abertschi** [comment]
Thanks for reaching out. I can look into it. Did you find other issues while using the app? A new major update is overdue.

**Comment by unseenlarks** [comment]
i didn't run into any issues, it worked perfectly.

**Comment by abertschi** [comment]
Would you be interested in contributing to this app by beta-testing some new builds before we publish new updates? Currently working on some new ad-detectors. Thanks and cheers.

**Comment by abertschi** [comment]
In particular,  spotify-lite, soundlcoud, accuradio, deezer, tidal

**Comment by unseenlarks** [comment]
certainly. i use Spotify Lite, Deezer and Accuradio.

**Comment by abertschi** [comment]
Great :), can you send me your preferred instant messaging platform to apps@abertschi.ch (Whatsapp, telegram, Twitter, messenger) and we can chit chat a bit what to do. May be easier than through GitHub issues. Thanks

**Comment by abertschi** [comment]
#84
