### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Haimu-ad** [abertschi/ad-free#82]
Reduce the volume of ads.

**Comment by abertschi** [comment]
Hi there, thanks for reaching out. Can you elaborate on this?

**Comment by Haimu-ad** [comment]
There are other apps on playstore like "mutify", "Spotmute" they have the feature to reduce the volume of the ad as the ad plays. Just check it out. Also, can you provide the support for "Spotify lite" app as well.

Thanks :-)

**Comment by abertschi** [comment]
thanks for the reply. I do not quite understand what's the purpose of reducing the volume when you can mute the ad completely. what would be the motivation to want this?

In 2017 or so I tried to publish this app in google playstore but it got declined as ad blocker of this kind were not allowed then.

A new major update is due, i can look into some more apps to add 👍

**Comment by abertschi** [comment]
Would you be interested in contributing to this app by beta-testing some new builds before we publish new updates? Are you a developer? thanks and cheers.

**Comment by Haimu-ad** [comment]
Also, checkout this app called "Ad-silence" on playstore. They have the
feature of muting ads in "Spotify lite" app. It is also open source.
Their github link:- https://github.com/aghontpi/Ad-silence

Thanks!

**Comment by abertschi** [comment]
Thank you for your interest in this project, for now I flag this request as wontfix.
